name = "{{WORKER_NAME}}"
main = "./worker.js"
compatibility_date = "2025-07-01"

[[routes]]
pattern = "{{DOMAIN}}{{AUDIO_PATH}}*"
zone_name = "{{DOMAIN}}"

[[routes]]
pattern = "{{DOMAIN}}{{RSS_PATH}}"
zone_name = "{{DOMAIN}}"

[observability.logs]
enabled = true

[[r2_buckets]]
binding = "PODCAST_ASSETS"
bucket_name = "{{BUCKET_NAME}}"

[vars]
AUDIO_PATH = "{{AUDIO_PATH}}"
RSS_PATH = "{{RSS_PATH}}"
RSS_LAST_MODIFIED = "{{RSS_LAST_MODIFIED}}"