name = "{{WORKER_NAME}}"
main = "./worker.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "{{DOMAIN}}{{AUDIO_PATH}}*", zone_name = "{{DOMAIN}}" },
  { pattern = "{{DOMAIN}}{{RSS_PATH}}", zone_name = "{{DOMAIN}}" }
]

[observability.logs]
enabled = true

[[r2_buckets]]
binding = "PODCAST_ASSETS"
bucket_name = "{{BUCKET_NAME}}"

[vars]
AUDIO_PATH = "{{AUDIO_PATH}}"