name = "{{WORKER_NAME}}"
main = "./worker.js"
compatibility_date = "2024-01-01"
account_id = "ecd2a3d65ecc1018f93da07542223581"

route = { pattern = "{{DOMAIN}}{{AUDIO_PATH}}*", zone_name = "{{DOMAIN}}" }

[[r2_buckets]]
binding = "PODCAST_ASSETS"
bucket_name = "{{BUCKET_NAME}}"

[vars]
AUDIO_PATH = "{{AUDIO_PATH}}"