name = "alexmarshall-website"
main = "./worker/index.js"
compatibility_date = "2025-07-01"
preview_urls = true
account_id = "ecd2a3d65ecc1018f93da07542223581"

[assets]
directory = "./_site"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "404-page"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "alexmarshall-assets"

[[routes]]
pattern = "alexmarshalltherapy.com"
custom_domain = true

[vars]
R2_PATHS = "[\"/assets/files/\"]"

[observability.logs]
enabled = true

[env.staging]
name = "alexmarshall-website-staging"
workers_dev = true
routes = []

[env.staging.assets]
directory = "./_site"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "404-page"

[[env.staging.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "alexmarshall-assets"

[env.staging.vars]
R2_PATHS = "[\"/assets/files/\"]"

[env.staging.observability.logs]
enabled = true
